
Runner.pages.PageSettings.addPageEvent("surat_editor",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Kemaskini16';if(!pageObj.buttonEventBefore['Kemaskini16']){pageObj.buttonEventBefore['Kemaskini16']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Kemaskini16']){pageObj.buttonEventAfter['Kemaskini16']=function(result,ctrl,pageObj,proxy,pageid,rowData){window.location="surat_maklumatsurat_edit.php?editid1="+result["txt"];}}
$('a[id=Kemaskini16]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Kemaskini16"+"_"+Runner.genId();var button_Kemaskini16=new Runner.form.Button({id:this.id,btnName:"Kemaskini16"});button_Kemaskini16.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("surat_editor",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button12';if(!pageObj.buttonEventBefore['New_Button12']){pageObj.buttonEventBefore['New_Button12']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['New_Button12']){pageObj.buttonEventAfter['New_Button12']=function(result,ctrl,pageObj,proxy,pageid,rowData){var win=window.open("ftpcopy/index.php","mywindow","location=1,status=1,scrollbars=1");win.focus();}}
$('a[id=New_Button12]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="New_Button12"+"_"+Runner.genId();var button_New_Button12=new Runner.form.Button({id:this.id,btnName:"New_Button12"});button_New_Button12.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("surat_editor",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Tambah_Penerima31';if(!pageObj.buttonEventBefore['Tambah_Penerima31']){pageObj.buttonEventBefore['Tambah_Penerima31']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Tambah_Penerima31']){pageObj.buttonEventAfter['Tambah_Penerima31']=function(result,ctrl,pageObj,proxy,pageid,rowData){window.open("TambahPenerima_list.php","mywindow","location=1,status=1,scrollbars=1");}}
$('a[id=Tambah_Penerima31]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Tambah_Penerima31"+"_"+Runner.genId();var button_Tambah_Penerima31=new Runner.form.Button({id:this.id,btnName:"Tambah_Penerima31"});button_Tambah_Penerima31.init({args:[pageObj,proxy,pageid]});});});