
Runner.pages.PageSettings.addPageEvent("menuview",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Kemaskini14';if(!pageObj.buttonEventBefore['Kemaskini14']){pageObj.buttonEventBefore['Kemaskini14']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Kemaskini14']){pageObj.buttonEventAfter['Kemaskini14']=function(result,ctrl,pageObj,proxy,pageid,rowData){window.location="suratview2_edit.php?editid1="+result["txt"];}}
$('a[id=Kemaskini14]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Kemaskini14"+"_"+Runner.genId();var button_Kemaskini14=new Runner.form.Button({id:this.id,btnName:"Kemaskini14"});button_Kemaskini14.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("menuview",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Kemaskini31';if(!pageObj.buttonEventBefore['Kemaskini31']){pageObj.buttonEventBefore['Kemaskini31']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Kemaskini31']){pageObj.buttonEventAfter['Kemaskini31']=function(result,ctrl,pageObj,proxy,pageid,rowData){window.location="suratview3_edit.php?editid1="+result["txt"];}}
$('a[id=Kemaskini31]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Kemaskini31"+"_"+Runner.genId();var button_Kemaskini31=new Runner.form.Button({id:this.id,btnName:"Kemaskini31"});button_Kemaskini31.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("menuview",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='New_Button9';if(!pageObj.buttonEventBefore['New_Button9']){pageObj.buttonEventBefore['New_Button9']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['New_Button9']){pageObj.buttonEventAfter['New_Button9']=function(result,ctrl,pageObj,proxy,pageid,rowData){var win=window.open("scan/index.php","mywindow","location=1,status=1,scrollbars=1");win.focus();}}
$('a[id=New_Button9]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="New_Button9"+"_"+Runner.genId();var button_New_Button9=new Runner.form.Button({id:this.id,btnName:"New_Button9"});button_New_Button9.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("menuview",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Hantar_Email_6';if(!pageObj.buttonEventBefore['Hantar_Email_6']){pageObj.buttonEventBefore['Hantar_Email_6']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Hantar_Email_6']){pageObj.buttonEventAfter['Hantar_Email_6']=function(result,ctrl,pageObj,proxy,pageid,rowData){alert("Email Telah Dihantar");}}
$('a[id=Hantar_Email_6]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Hantar_Email_6"+"_"+Runner.genId();var button_Hantar_Email_6=new Runner.form.Button({id:this.id,btnName:"Hantar_Email_6"});button_Hantar_Email_6.init({args:[pageObj,proxy,pageid]});});});